[tool:pytest]
DJANGO_SETTINGS_MODULE = euniforms.tests.settings
python_files = tests.py test_*.py *_tests.py
python_classes = *Test *TestCase
python_functions = test_*
addopts = --tb=short --strict-markers --disable-warnings --ds=euniforms.tests.settings
testpaths = euniforms/tests
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests