# Generated by Django 4.2.30 on 2026-06-01 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can access the Forms app and fill out eligible forms'), ('manage_forms', 'Can create, edit and delete forms and view all responses')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True, help_text='Shown to people before they fill out the form.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_multiple', models.BooleanField(default=False, help_text='Allow a person to submit this form more than once.')),
                ('notify_on_submit', models.BooleanField(default=True, help_text='Send an Auth notification to viewers when a response is submitted.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restricted_groups', models.ManyToManyField(blank=True, help_text='Only members of these groups may fill out the form. Leave empty to allow any logged-in user.', related_name='+', to='auth.group')),
                ('viewer_groups', models.ManyToManyField(blank=True, help_text='Members of these groups may read the responses to this form.', related_name='+', to='auth.group')),
            ],
            options={
                'ordering': ['-created_at'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_character_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('main_character_name', models.CharField(blank=True, max_length=254)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='euniforms.form')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=254)),
                ('help_text', models.CharField(blank=True, max_length=254)),
                ('field_type', models.CharField(choices=[('SHORT_TEXT', 'Short text'), ('LONG_TEXT', 'Paragraph text'), ('SINGLE_CHOICE', 'Single choice'), ('MULTI_CHOICE', 'Multiple choice'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('BOOLEAN', 'Yes / No'), ('EVE_CHARACTER', 'EVE character (verified)')], default='SHORT_TEXT', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='euniforms.form')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label', models.CharField(max_length=254)),
                ('field_type', models.CharField(max_length=20)),
                ('value', models.JSONField(blank=True, null=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='euniforms.formfield')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='euniforms.formresponse')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('value', models.CharField(max_length=254)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='euniforms.formfield')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'default_permissions': (),
            },
        ),
    ]
