# Generated by Django 4.2.30 on 2026-06-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euniforms', '0002_add_discord_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='introduction_text',
            field=models.TextField(blank=True, help_text='Additional text shown at the top of the question sheet when filling out the form.'),
        ),
    ]
