# Generated by Django for the EVE Uni Forms app

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('euniforms', '0006_add_free_text_field_type'),
    ]

    operations = [
        # Create FormCollaborator model
        migrations.CreateModel(
            name='FormCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='euniforms.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added_at'],
                'default_permissions': (),
            },
        ),

        # Add answer limit fields to Form model
        migrations.AddField(
            model_name='form',
            name='answer_limit_type',
            field=models.CharField(
                choices=[
                    ('UNLIMITED', 'Unlimited submissions'),
                    ('ONCE_PER_ACCOUNT', 'Once per account'),
                    ('LIMITED_PER_ACCOUNT', 'Limited submissions per account')
                ],
                default='ONCE_PER_ACCOUNT',
                help_text='How to limit submissions per account.',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='form',
            name='answer_limit',
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of submissions per account (only used with 'Limited submissions per account').",
                null=True
            ),
        ),
        migrations.AddField(
            model_name='form',
            name='limit_window_days',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Optional: Reset the limit every N days. Leave empty for no reset.',
                null=True
            ),
        ),

        # Add unique constraint and indexes for FormCollaborator
        migrations.AlterUniqueTogether(
            name='formcollaborator',
            unique_together={('form', 'user')},
        ),
        migrations.AddIndex(
            model_name='formcollaborator',
            index=models.Index(fields=['form', 'user'], name='collaborator_form_user_idx'),
        ),
    ]