# Generated by Django for the EVE Uni Forms app

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('euniforms', '0006_add_free_text_field_type'),
    ]

    operations = [
        # Add collaborator groups field to Form model
        migrations.AddField(
            model_name='form',
            name='collaborator_groups',
            field=models.ManyToManyField(
                blank=True,
                help_text='Members of these groups may edit this form and its questions.',
                related_name='editable_forms',
                to='auth.group'
            ),
        ),

        # Add answer limit fields to Form model
        migrations.AddField(
            model_name='form',
            name='answer_limit_type',
            field=models.CharField(
                choices=[
                    ('UNLIMITED', 'Unlimited submissions'),
                    ('ONCE_PER_ACCOUNT', 'Once per account'),
                    ('LIMITED_PER_ACCOUNT', 'Limited submissions per account')
                ],
                default='ONCE_PER_ACCOUNT',
                help_text='How to limit submissions per account.',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='form',
            name='answer_limit',
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of submissions per account (only used with 'Limited submissions per account').",
                null=True
            ),
        ),
        migrations.AddField(
            model_name='form',
            name='limit_window_days',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Optional: Reset the limit every N days. Leave empty for no reset.',
                null=True
            ),
        ),
    ]